export const AUTH_SUBMIT = 'AUTH_SUBMIT';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const CHANGE_AUTH = 'CHANGE_AUTH';
export const AUTH_STEP = 'AUTH_STEP';
export const UPDATE_RESTRICTIONS = 'UPDATE_RESTRICTIONS';
